name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: ./Proyecto-Desarrollo3/Library
          key: Library-${{ hashFiles('./Proyecto-Desarrollo3/Assets/**', './Proyecto-Desarrollo3/Packages/**', './Proyecto-Desarrollo3/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

#Build name

   - name: Set build name

     id: buildName

     run: |

     sudo apt-get update

     echo "DATE=$(date +'%y%m%d')" >> $GITHUB_ENV

      

    # Upload Artifact

   - name: Create Artifact

     uses: actions/upload-artifact@v3

     with:

      name: build_${{ env.DATE }}

      path: build